DECLARE @tableName varchar(255),
		@sql	varchar(1000)

DECLARE MY_CURSOR CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT name
FROM  SYSOBJECTS
WHERE xtype = 'U';

OPEN MY_CURSOR
FETCH NEXT FROM MY_CURSOR INTO @tableName
WHILE @@FETCH_STATUS = 0
BEGIN 
    SET @sql = 'DROP TABLE DataSync.' +@tableName
    EXEC (@sql)
    FETCH NEXT FROM MY_CURSOR INTO @tableName
END
CLOSE MY_CURSOR
DEALLOCATE MY_CURSOR

